server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet


  datasource:
    url: jdbc:postgresql://localhost:5432/ordering_system
    username: postgres
    password: 19671970
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true